self.addEventListener("install", function(e)
{
	e.waitUntil(
		caches.open("adventurer").then(function(cache)
		{
			return cache.addAll([
				"/",
				"/index.html",
				"/styles/index.css",
				"/scripts/index.js",
				"/images/female.png",
				"/images/male.png",
				"/images/Liver of Steel.png",
				"/images/tasty tart.png",
				"/images/Frosty's Frosty mug.png",
				"/images/Warbear gyro.png",
				"/images/devil dog.png",
				"/images/Pastamancer-m-3.png",
				"/images/tuxedo shirt.png",
				"/images/Plain pizza.png",
				"/images/Feast of Boris.png",
				"/images/jar of fermented pickle juice.png",
				"/images/Deluxe Mr. Klaw \"Skill\" Crane Game.png",
				"/images/optimal dog.png",
				"/images/A Relaxing Hot Tub.png",
				"/images/hot hi mein.png",
				"/images/Pastamancer-m-1.png",
				"/images/Dreadsylvania.png",
				"/images/Disco Bandit-f-1.png",
				"/images/Divine.png",
				"/images/liquid shifting time weirdness.png",
				"/images/fancy opera glasses.png",
				"/images/Clan Speakeasy.png",
				"/images/Nightcap.png",
				"/images/twinkly wad.png",
				"/images/Bee's Knees.png",
				"/images/distention pill.png",
				"/images/Accordion Thief-m-3.png",
				"/images/prismatic wad.png",
				"/images/Play Strategically.png",
				"/images/New Zealand iced tea.png",
				"/images/Seal Clubber-f-1.png",
				"/images/Sauceror-f-3.png",
				"/images/Turtle Tamer-m-2.png",
				"/images/Ol' Scratch's salad fork.png",
				"/images/Turtle Tamer-f-3.png",
				"/images/Hobopolis.png",
				"/images/Unconscious Collective Dream Jar.png",
				"/images/sleeping dog.png",
				"/images/Turtle Tamer-f-2.png",
				"/images/Ode to Booze.png",
				"/images/Purse Rat.png",
				"/images/Spleen of Steel.png",
				"/images/Sauceror-m-2.png",
				"/images/Disco Bandit-f-3.png",
				"/images/coffee pixie stick.png",
				"/images/antimatter wad.png",
				"/images/Disco Bandit-m-1.png",
				"/images/Ish Kabibble.png",
				"/images/Legendary Appetite.png",
				"/images/bottle of single-barrel whiskey.png",
				"/images/Lock.png",
				"/images/Instant Karma.png",
				"/images/chilly dog.png",
				"/images/Ultra Mega Sour Ball.png",
				"/images/garish pinky ring.png",
				"/images/Black pudding.png",
				"/images/voodoo snuff.png",
				"/images/The Blender.png",
				"/images/glass of \"milk\".png",
				"/images/VIP Lounge.png",
				"/images/Pastamancer-f-2.png",
				"/images/Phonus Balonus.png",
				"/images/insanely spicy bean burrito.png",
				"/images/Accordion Thief-m-2.png",
				"/images/Hamburger.png",
				"/images/bottle of popskull.png",
				"/images/Accordion Thief-f-3.png",
				"/images/Seal Clubber-f-3.png",
				"/images/Pastamancer-m-2.png",
				"/images/bottle of rum.png",
				"/images/packet of beer nuts.png",
				"/images/synthetic dog hair pill.png",
				"/images/Turtle Tamer-f-1.png",
				"/images/A Pool Table.png",
				"/images/Labór Day.png",
				"/images/Pastamancer-f-1.png",
				"/images/unidentified jerky.png",
				"/images/Stomach of Steel.png",
				"/images/savage macho dog.png",
				"/images/Mojo Filter.png",
				"/images/Stuffed teddy butler.png",
				"/images/St. Sneaky Pete's Day.png",
				"/images/grim fairy tale.png",
				"/images/Stuffed mink.png",
				"/images/video games hot dog.png",
				"/images/Seal Clubber-m-1.png",
				"/images/epic cluster.png",
				"/images/Seal Clubber-f-2.png",
				"/images/Hard Drinker.png",
				"/images/Hunger™ Sauce.png",
				"/images/Flivver.png",
				"/images/Clan hot dog stand.png",
				"/images/soft green echo eyedrop antidote martini.png",
				"/images/Ice Island Long Tea.png",
				"/images/extra-greasy slider.png",
				"/images/Sockdollager.png",
				"/images/Turtle Tamer-m-3.png",
				"/images/Dreadsylvanian hot pocket.png",
				"/images/Breathetastic™ Premium Canned Air.png",
				"/images/ghost dog.png",
				"/images/Ye Olde Meade.png",
				"/images/spice melange.png",
				"/images/handful of Smithereens.png",
				"/images/Accordion Thief-f-2.png",
				"/images/long pork lasagna.png",
				"/images/Adventurous Clicks.png",
				"/images/Disco Bandit-m-2.png",
				"/images/Hot Socks.png",
				"/images/thermos of \"whiskey\".png",
				"/images/Disco Bandit-m-3.png",
				"/images/Fog Murderer.png",
				"/images/cup of \"tea\".png",
				"/images/Dreadsylvanian hot toddy.png",
				"/images/Stuffed treasure chest.png",
				"/images/April Shower.png",
				"/images/Lunch Like a King.png",
				"/images/junkyard dog.png",
				"/images/designer handbag.png",
				"/images/Play Stylishly.png",
				"/images/one with everything.png",
				"/images/Seal Clubber-m-3.png",
				"/images/Sauceror-f-1.png",
				"/images/Lucky Lindy.png",
				"/images/Dog Tired.png",
				"/images/Stuffed monocle.png",
				"/images/milk of magnesium.png",
				"/images/wet dog.png",
				"/images/agua de vida.png",
				"/images/Hollow Leg.png",
				"/images/Paint A Vulgar Pitcher.png",
				"/images/Sauceror-f-2.png",
				"/images/basic hot dog.png",
				"/images/An Olympic-Sized Swimming Pool.png",
				"/images/bejeweled cufflinks.png",
				"/images/giant designer sunglasses.png",
				"/images/Pastamancer-f-3.png",
				"/images/groose grease.png",
				"/images/Orange.png",
				"/images/sly dog.png",
				"/images/frozen banquet.png",
				"/images/Stuffed Meat.png",
				"/images/Clan Basement.png",
				"/images/Hodgman's Blanket.png",
				"/images/powdered gold.png",
				"/images/Stuffed tin of caviar.png",
				"/images/A Looking Glass.png",
				"/images/The Opossum.png",
				"/images/Empty.png",
				"/images/Stuffed key.png",
				"/images/Play Aggressively.png",
				"/images/Sauceror-m-1.png",
				"/images/Accordion Thief-f-1.png",
				"/images/munchies pill.png",
				"/images/Disco Bandit-f-2.png",
				"/images/Wrecked Generator.png",
				"/images/Sloppy Jalopy.png",
				"/images/The Slimetube.png",
				"/images/Seal Clubber-m-2.png",
				"/images/Stuffed Baron von Ratsworth.png",
				"/images/Turtle Tamer-m-1.png",
				"/images/Your Very Own Clan.png",
				"/images/Sauceror-m-3.png",
				"/images/Accordion Thief-m-1.png"
			]).then(function() { self.skipWaiting(); });
		})
	);
});

self.addEventListener("activate", function(e)
{
	e.waitUntil(self.clients.claim());
});

self.addEventListener("fetch", function(e)
{
	e.respondWith(
		caches.match(e.request).then(function(res)
		{
			return res || fetch(e.request);
		})
	);
});
